# fly.toml app configuration file generated for revendedora-natura on 2025-05-10T20:02:24-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'revendedora-natura'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1024'
