# Generated by Django 5.2 on 2025-04-27 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='São Roque', max_length=100, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.CharField(default='', max_length=20, verbose_name='CPF/CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='SP', max_length=2, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(default='', max_length=250, verbose_name='Logradouro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default=0, max_length=10, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
